### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by stevenvachon** [iest/buttery-scroll#2]
It's not working in Firefox (desktop) for me. Please provide a demo for quick testing to rule out the library as the cause of the error.

**Comment by stevenvachon** [comment]
Firefox will scroll `document.documentElement` but not `document.body`.
Webkit/Blink will scroll `document.body` but not `document.documentElement`.

http://stackoverflow.com/questions/19635188/why-is-body-scrolltop-deprecated

Suggestions?

**Comment by iest** [comment]
I just tried [the demo](http://codepen.io/iest/pen/VYpXJy) on Firefox 32.0.3 on a Mac and it works fine.

This library doesn't depend on body or document or anything — it just needs a `scrollable` element. Your issue seems to be deciding which element to scroll (`document.documentElement` or `document.body` depending on the browser, in your case).

I'm closing this as it's an issue outside the scope of this library. Good luck with your issue!
